name: CI

# ─────────────────────────────
# 1. Déclencheurs
# ─────────────────────────────
on:
  push:
    branches: [main]          # pipeline à chaque commit sur main
  pull_request:               # pipeline pour chaque PR (toutes branches)
  # Planification quotidienne à 21 h Paris :
  schedule:
    - cron:  '0 19 * * *'     # 21 h CEST (été) – 20 h CET (hiver)
    - cron:  '0 20 * * *'     # 21 h CET (hiver)
  # Lancement manuel depuis l’UI GitHub
  workflow_dispatch:
    inputs:
      browser:
        description: "Navigateur : chrome, firefox, edge…"
        required: false
        default: "chrome"

# Empêche deux exécutions simultanées sur la même branche
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

# ─────────────────────────────
# 2. Job principal : tests Cypress
# ─────────────────────────────
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Décommente cet encadré si tes tests ont besoin d’un serveur local
      # - name: Start app
      #   run: |
      #     npm start &
      #     sleep 10    # laisse le temps au serveur de s’amorcer
      #   env:
      #     NODE_ENV: test

      - name: Run Cypress (sans Dashboard)
        uses: cypress-io/github-action@v6.8.0
        with:
          browser: ${{ inputs.browser || 'chrome' }}
          # record et parallel sont absents → pas de dépendance à Cypress Cloud

      - name: Upload artefacts (vidéos, screenshots)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
            cypress/results
