name: CI

# ─────────────────────────────
# 1. Déclencheurs
# ─────────────────────────────
on:
  push:
    branches: [main]          # pipeline à chaque commit sur main
  pull_request:               # pipeline pour chaque PR (toutes branches)
  # Planification quotidienne à 21 h Paris :
  schedule:
    # Chaque jour à 19:00 UTC ≃ 21:00 CEST (22:00 CET)
    - cron:  '0 19 * * *'
  # Lancement manuel depuis l’UI GitHub
  workflow_dispatch:
    inputs:
      browser:
        description: "Navigateur : chrome, firefox, edge…"
        required: false
        default: "chrome"

# Empêche deux exécutions simultanées sur la même branche
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

# ─────────────────────────────
# 2. Job principal : tests Cypress
# ─────────────────────────────
jobs:
  cypress-run:
    runs-on: ubuntu-latest       
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'            

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress
        uses: cypress-io/github-action@v6.8.0
        with:
          record: true
          parallel: true
          browser: ${{ inputs.browser || 'chrome' }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          SAUCE_USERNAME:      ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY:    ${{ secrets.SAUCE_ACCESS_KEY }}

      - name: Upload artefacts
        if: always()              
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
            cypress/results
